### ISSUE TITLE
Can you provide AP50 for each category on the SHIFT dataset?

### ISSUE THREAD

**Issue by HDUyiming** [jichengyuan/Cooperitive_Students#1]
我想引用一下您的工作，但是我缺少您在SHIFT上各个类别的具体性能，如果可以，您能否提供一下您的方法以及2CPNet、AT、SADA、FourierDA在ACDC的各个类别的上的AP性能吗？

**Comment by jichengyuan** [comment]
Hi @HDUyiming , 

thank you for getting interested in our work,

sure, here are the eval-results of our model on SHIFT:

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.338
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.510
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.373
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.123
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.601
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.789
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.259
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.384
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.388
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.175
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.656
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.829
=======================Evaluated classwise AP is below:=============================
| category   | AP50   | category   | AP50   | category   | AP50   |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| pedestrian | 50.864 | car        | 56.030 | truck      | 57.212 |
| bus        | 64.477 | motorcycle | 22.163 | bicycle    | 55.486 | ,

for the performance of 2PCNet, 

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.319
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.491
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.349
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.113
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.568
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.247
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.362
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.368
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.164
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.619
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.784
=======================Evaluated classwise AP is below:=============================
| category   | AP50   | category   | AP50   | category   | AP50   |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| pedestrian | 45.000 | car        | 56.163 | truck      | 55.431 |
| bus        | 64.493 | motorcycle | 18.350 | bicycle    | 55.165 | 

for the performance of AT, 

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.292
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.448
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.330
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.097
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.524
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.680
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.226
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.334
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.336
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.138
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.585
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.725
=======================Evaluated classwise AP is below:=============================
| category   | AP50   | category   | AP50   | category   | AP50   |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| pedestrian | 43.156 | car        | 48.274 | truck      | 51.316 |
| bus        | 57.436 | motorcycle | 17.817 | bicycle    | 51.075 | 

for the performance of FDA, 

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.303
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.471
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.327
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.102
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.550
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.712
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.350
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.355
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.155
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.603
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.762
=======================Evaluated classwise AP is below:=============================
| category   | AP50   | category   | AP50   | category   | AP50   |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| pedestrian | 46.359 | car        | 52.314 | truck      | 50.657 |
| bus        | 58.646 | motorcycle | 20.688 | bicycle    | 53.802 | 

For the SADA, I just resue this repo (https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch) and did not evalute class-wisely.

If you have any other questions, fell free to post here ;))

**Comment by HDUyiming** [comment]
谢谢您的回复！我将在我们未来的文章中引用您的工作。祝您工作顺利，生活愉快！

**Comment by HDUyiming** [comment]
请问这个代码框架如何得到各个类别的AP50呢？
