### ISSUE TITLE
Ask for JSON of bdd100k and shift

### ISSUE THREAD

**Issue by wSwilder** [jichengyuan/Cooperitive_Students#2]
Hello author, I want to reproduce your paper, could you please provide json files of bdd100k and shift?millions of thanks!

**Comment by jichengyuan** [comment]
Hi @wSwilder,

sure, we follow the data-split in 2PCNet, you could find them here:https://www.dropbox.com/scl/fo/258uzp6i0dz17zsj234r6/h?rlkey=kb6brfk1oqc1ddsa3ulz8v9ei&dl=0

**Comment by wSwilder** [comment]
During the training process, I encountered a new problem, I will get the following error: augmentation error:  high <= 0, where does the problem occur?

**Comment by wSwilder** [comment]
I've handled it,is occurs in the 'aug',where h_new and w_new should be positive value

**Comment by jichengyuan** [comment]
great!
